const crypto = require('crypto');

// Deterministic hash for lookup tokens (password reset, invite) stored at
// rest. Deliberately NOT bcrypt: bcrypt is for passwords precisely because
// it must be slow and non-deterministic (can't be looked up by equality) —
// these tokens are single-use, short-lived, high-entropy random values
// generated by us, so a fast deterministic hash is both sufficient and
// necessary to keep the existing indexed equality lookup working.
function hashToken(token) {
  return crypto.createHash('sha256').update(token).digest('hex');
}

module.exports = { hashToken };
